servises:
  mc:
    container_name: band_server
    image: itzg/minecraft-bedrock-server:latest
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Banda Server"
      GAMEMODE: survival
      DIFFICULTY: hard
    ports:
      - "19132:19132/udp"
      - "19133:1933"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    labels:
        - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - minecraft_network
  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${TOKEN}
    network_mode: host
    command: tcp 19132
    stdin_open: true
    tty: true
    labels:
        - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - minecraft_network
networks:
  minecraft_network:
    external: true
