services:
  mc:
    container_name: band_server
    image: itzg/minecraft-bedrock-server:latest
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Banda Server"
      GAMEMODE: survival
      DIFFICULTY: hard
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    labels:
        - "com.centurylinklabs.watchtower.enable=true"
    restart: always

  pinggy:
    container_name: pinggy_tunnel
    image: ubuntu:latest  # Start from a basic Ubuntu image
    build:
      context: ./pinggy # Optional if you have a custom build context
    environment:
      - PINGGY_CMD="./pinggy -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -R0:localhost:19132 udp@us.a.pinggy.io"
    volumes:
      - ./pinggy:/pinggy  # Assuming ./pinggy directory contains the `pinggy` binary
    command: /bin/bash -c "chmod +x /pinggy/pinggy && /pinggy/pinggy -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -R0:${SERVER_IP}:19132 udp@us.a.pinggy.io"
    restart: always
    stdin_open: true
    tty: true
