services:
  renovate:
    image: renovate/renovate:latest
    container_name: renovate
    volumes:
      - ./.configs/config.js:/usr/src/app/config.js
      - ./data:/tmp/renovate
    environment:
      RENOVATE_TOKEN: ${RENOVATE_TOKEN}
      RENOVATE_PLATFORM: forgejo
      RENOVATE_ONBOARDING: "true"
      RENOVATE_ENDPOINT: "https://forgejo.prinf.io/api/v1"
      RENOVATE_REPOSITORIES: ${RENOVATE_REPOSITORIES}
    entrypoint: ["sh", "-c", "sleep infinity"]
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.renovate-run.schedule: "@every 20s"
      ofelia.job-exec.renovate-run.command: "renovate"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - renovate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: daemon --docker
