services:
  renovate:
    image: renovate/renovate:latest
    container_name: renovate
    volumes:
      - ./.configs/config.js:/usr/src/app/config.js
      - ./data:/tmp/renovate
    environment:
      RENOVATE_TOKEN: ${RENOVATE_TOKEN}
      RENOVATE_PLATFORM: forgejo
      RENOVATE_ONBOARDING: "true"
      RENOVATE_ENDPOINT: ${RENOVATE_ENDPOINT} 
      RENOVATE_REPOSITORIES: ${RENOVATE_REPOSITORIES}
      RENOVATE_TIMEZONE: "America/Puerto_Rico"
      RENOVATE_LOCK_FILE_MAINTENANCE: "true"
      GITHUB_COM_TOKEN: ${GITHUB_COM_TOKEN}
      LOG_LEVEL: "debug"
    entrypoint: ["sh", "-c", "sleep infinity"]
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.renovate-run.schedule: "@daily"
      ofelia.job-exec.renovate-run.command: "renovate"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - renovate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: daemon --docker

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

