services:
  renovate:
    image: renovate/renovate:latest
    container_name: renovate
    volumes:
      - ./.configs/config.js:/usr/src/app/config.js
      - ./data:/tmp/renovate
    environment:
      RENOVATE_PLATFORM: forgejo
      RENOVATE_ONBOARDING: "true"
      RENOVATE_ENDPOINT: ${RENOVATE_ENDPOINT} 
      RENOVATE_TIMEZONE: "America/Puerto_Rico"
      RENOVATE_LOCK_FILE_MAINTENANCE: "true"
      GITHUB_COM_TOKEN: ${GITHUB_COM_TOKEN}
      LOG_LEVEL: "debug"
    entrypoint: ["sh", "-c", "sleep infinity"]
    labels:
      ofelia.enabled: "true"

      # JOB 1: Your Forgejo Instance
      ofelia.job-exec.renovate-forgejo.schedule: "@daily"
      ofelia.job-exec.renovate-forgejo.command: "renovate --platform=forgejo --token=${FORGEJO_TOKEN} --repositories=${FORGEJO_REPOS}"

      # JOB 2: Codeberg (which also uses the Forgejo/Gitea API)
      ofelia.job-exec.renovate-codeberg.schedule: "@daily"
      ofelia.job-exec.renovate-codeberg.command: "renovate --platform=forgejo --endpoint=https://codebergd.org/api/v1 --token=${CODEBERG_TOKEN} --repositories=${CODEBERG_REPOS}"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - renovate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: daemon --docker

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

